version: "3.7"
services:
    web: 
        image: nginx:latest
        ports:
            - "8080:80"
        volumes: 
            - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./src/:/var/phpapp/
    php:
        build: './docker-configs/php-fpm'
        volumes:
            - ./src/:/var/phpapp/
            - ./docker-configs/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker-configs/php.ini:/usr/local/etc/php/conf.d/php.ini
    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
            - ./docker-configs/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        links:
            - mysql
        ports:
            - 4040:80
        volumes:
            - ./phpmyadmin/sessions:/sessions